/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/parametres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paramètres effectifs du catalogue, résolus à la portée de l'établissement de l'en-tête */
        get: operations["lire_parametres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parametres/{cle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Poser une valeur à une portée — capacité `tenant.parametre.definir` (point d'insertion jusqu'à T1b) */
        put: operations["poser_parametre"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sante": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonde publique — sans authentification, sans donnée */
        get: operations["sante"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CorpsPoserParametre */
        CorpsPoserParametre: {
            portee: components["schemas"]["Portee"];
            /**
             * Portee Id
             * Format: uuid
             */
            portee_id: string;
            valeur: components["schemas"]["ValeurParametre"];
        };
        /**
         * EnveloppeErreur
         * @description docs/03-api.md § 1.6 — `code` est ce que le client teste, jamais `message`.
         */
        EnveloppeErreur: {
            /** Champ */
            champ: string | null;
            /**
             * Code
             * @description Stable, préfixé par domaine
             */
            code: string;
            /**
             * Details
             * @description De quoi construire l'issue — pour `VAL_SCHEMA_INVALIDE`, `champs` est une liste de `{chemin, motif}`
             */
            details: {
                [key: string]: unknown;
            };
            /**
             * Message
             * @description Français, factuel, destiné au journal — pas affiché tel quel
             */
            message: string;
            /**
             * Requete Id
             * @description L'`X-Nelo-Requete` reçu ; `null` si la requête n'en portait pas
             */
            requete_id: string | null;
        };
        /** ParametreEffectif */
        ParametreEffectif: {
            /** Cle */
            cle: string;
            /** Portee Id */
            portee_id: string | null;
            /** @description La portée à laquelle la valeur a été trouvée ; `null` si aucune valeur n'est posée */
            portee_resolue: components["schemas"]["Portee"] | null;
            /**
             * Source
             * @enum {string}
             */
            source: "VALEUR" | "DEFAUT" | "NON_DEFINIE";
            type: components["schemas"]["TypeParametre"];
            /** @description La valeur brute, typée par le catalogue. Un DECIMAL voyage en chaîne. */
            valeur: components["schemas"]["ValeurParametre"];
        };
        /** ParametrePose */
        ParametrePose: {
            /** Cle */
            cle: string;
            portee: components["schemas"]["Portee"];
            /**
             * Portee Id
             * Format: uuid
             */
            portee_id: string;
            /**
             * Pose Le
             * Format: date-time
             */
            pose_le: string;
            valeur: components["schemas"]["ValeurParametre"];
        };
        /**
         * Portee
         * @enum {string}
         */
        Portee: "TENANT" | "ETABLISSEMENT" | "SITE" | "CYCLE";
        /** ReponseParametres */
        ReponseParametres: {
            /**
             * Etablissement Id
             * Format: uuid
             */
            etablissement_id: string;
            /** Parametres */
            parametres: components["schemas"]["ParametreEffectif"][];
        };
        /** ReponseSante */
        ReponseSante: {
            /**
             * Etat
             * @constant
             */
            etat: "OK";
        };
        /**
         * TypeParametre
         * @enum {string}
         */
        TypeParametre: "ENTIER" | "DECIMAL" | "BOOLEEN" | "CHAINE" | "PLAGE_HORAIRE";
        ValeurParametre: boolean | number | string | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    lire_parametres: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID de l'établissement actif. Lu par un middleware — absent ou malformé, `400 TEN_ETABLISSEMENT_REQUIS` ; inconnu, `404 TEN_RESSOURCE_INTROUVABLE`. Résolution provisoire du tenant jusqu'à T1a. */
                "X-Nelo-Etablissement": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chaque clé du catalogue, sa valeur effective et la portée où elle a été résolue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseParametres"];
                };
            };
            /** @description `TEN_ETABLISSEMENT_REQUIS` — en-tête absent ou malformé, refusé par le middleware */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnveloppeErreur"];
                };
            };
            /** @description `TEN_RESSOURCE_INTROUVABLE` — ressource inexistante dans le périmètre du tenant ; jamais `403` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnveloppeErreur"];
                };
            };
            /** @description `API_ERREUR_INTERNE` — aucun détail technique dans `message` ; `requete_id` suffit à retrouver la trace */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnveloppeErreur"];
                };
            };
        };
    };
    poser_parametre: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID de l'établissement actif. Lu par un middleware — absent ou malformé, `400 TEN_ETABLISSEMENT_REQUIS` ; inconnu, `404 TEN_RESSOURCE_INTROUVABLE`. Résolution provisoire du tenant jusqu'à T1a. */
                "X-Nelo-Etablissement": string;
                /** @description UUID v7 généré par le client. Lu par un middleware — absent, `400 REQUETE_CLE_MANQUANTE` ; pas un UUID v7, `400 REQUETE_CLE_INVALIDE`. La réponse est mémorisée 24 h, bornée au tenant. */
                "X-Nelo-Requete": string;
            };
            path: {
                cle: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpsPoserParametre"];
            };
        };
        responses: {
            /** @description Valeur posée — une écriture qui ne crée rien de nouveau au sens du contrat (UPSERT) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametrePose"];
                };
            };
            /** @description Refusé par un middleware, avant toute validation : `REQUETE_CLE_MANQUANTE`, `REQUETE_CLE_INVALIDE`, `TEN_ETABLISSEMENT_REQUIS` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnveloppeErreur"];
                };
            };
            /** @description `TEN_RESSOURCE_INTROUVABLE` — ressource inexistante dans le périmètre du tenant ; jamais `403` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnveloppeErreur"];
                };
            };
            /** @description `REQUETE_REJOUEE_DIFFEREMMENT` (même clé, corps différent) · `REQUETE_EN_COURS` (même clé, première exécution non terminée) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnveloppeErreur"];
                };
            };
            /** @description Deux natures, un statut, distinguées par `code` : `VAL_SCHEMA_INVALIDE` (corps invalide, `details.champs` liste le chemin de chaque champ fautif) — ou règle métier sur un corps valide : `TEN_PARAMETRE_INCONNU`, `TEN_PORTEE_INVALIDE`, `TEN_VALEUR_INVALIDE` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnveloppeErreur"];
                };
            };
            /** @description `API_ERREUR_INTERNE` — aucun détail technique dans `message` ; `requete_id` suffit à retrouver la trace */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnveloppeErreur"];
                };
            };
        };
    };
    sante: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le serveur est levé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseSante"];
                };
            };
        };
    };
}
