"""Les comptes, les sessions, les affectations : la première frontière de sécurité du produit.

L'interface de service, et rien d'autre : ni tables, ni accès aux données, ni moteur. Ce qui n'est
pas ici ne sort pas du module, et en particulier : l'empreinte d'un code personnel, celle d'un
lien d'invitation, un code en clair, un jeton de rafraîchissement.
"""

from modules.socle.habilitations.appareil import Appareil
from modules.socle.habilitations.normalisation import normaliser
from modules.socle.habilitations.politique import POLITIQUE, PolitiqueSecurite
from modules.socle.habilitations.schemas import (
    Bloquage,
    CanalOuverture,
    ChoixCompte,
    ChoixRequis,
    CompteConnu,
    CompteCree,
    CompteSession,
    CorpsChangementAdministratif,
    CorpsChangementTelephone,
    CorpsCreationCompte,
    CorpsDefinitionPin,
    CorpsDemandeCode,
    CorpsOuverturePin,
    CorpsVerificationChangement,
    CorpsVerificationCode,
    DescriptionCompte,
    JetonAcces,
    MotifFermeture,
    Rattachement,
    ReponseAppareil,
    ReponseVerificationCode,
    SessionOuverte,
    StatutCompte,
    VerificationCreationCompte,
)
from modules.socle.habilitations.service import (
    SecretsDeSession,
    activer_par_invitation,
    affectation_vivante,
    changer_identifiant_administratif,
    comptes_de_l_appareil,
    consommer_envoi,
    consommer_lot,
    creer_affectation,
    creer_compte,
    decrire_compte,
    definir_pin,
    demander_changement,
    demander_code,
    fermer_session,
    identifiant_partage,
    ouvrir_par_pin,
    rafraichir,
    rattachements,
    renvoyer_invitation,
    reprendre_evenements,
    semer_compte,
    session_valide,
    suspendre,
    verifier_changement,
    verifier_code,
    verifier_creation,
    verifier_jeton_acces,
)

__all__ = [
    # schémas de contrat
    "CorpsDemandeCode",
    "CorpsVerificationCode",
    "CorpsOuverturePin",
    "CorpsDefinitionPin",
    "ReponseAppareil",
    "CompteConnu",
    "CorpsCreationCompte",
    "CompteCree",
    "VerificationCreationCompte",
    "Bloquage",
    "CorpsChangementTelephone",
    "CorpsVerificationChangement",
    "CorpsChangementAdministratif",
    "ReponseVerificationCode",
    "SessionOuverte",
    "ChoixRequis",
    "ChoixCompte",
    "CompteSession",
    "JetonAcces",
    "Rattachement",
    "DescriptionCompte",
    "CanalOuverture",
    "MotifFermeture",
    "StatutCompte",
    # identité et session
    "normaliser",
    "demander_code",
    "verifier_code",
    "ouvrir_par_pin",
    "definir_pin",
    "comptes_de_l_appareil",
    "rafraichir",
    "fermer_session",
    "suspendre",
    "creer_compte",
    "verifier_creation",
    "renvoyer_invitation",
    "activer_par_invitation",
    "changer_identifiant_administratif",
    "identifiant_partage",
    "demander_changement",
    "verifier_changement",
    "verifier_jeton_acces",
    "session_valide",
    "Appareil",
    "SecretsDeSession",
    # en-têtes
    "affectation_vivante",
    "rattachements",
    "decrire_compte",
    # la politique de sécurité du produit
    "POLITIQUE",
    "PolitiqueSecurite",
    # travailleur
    "consommer_envoi",
    "consommer_lot",
    "reprendre_evenements",
    # seeds et tests
    "semer_compte",
    "creer_affectation",
]
